import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {

    const monthName = 'October';
    const year = '2026';
    const amount = '1400';


  await page.goto('https://care.konasl.me/apps/login/index.php');
  await page.getByRole('textbox', { name: 'Employee ID *' }).click();
  await page.getByRole('textbox', { name: 'Employee ID *' }).fill('202526');
  await page.getByRole('textbox', { name: 'PIN *' }).click();
  await page.getByRole('textbox', { name: 'PIN *' }).fill('252525');
  await page.getByRole('button', { name: ' Login' }).click();
//  await page.getByRole('listitem').filter({ hasText: 'Expenditure Claim' }).click();
  await page.getByRole('link', { name: ' Expenditure Claim' }).click();

  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('ash');
  await page.locator('tr:nth-child(3) > td:nth-child(7) > .btn').click();
  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
//   await page.getByPlaceholder('Search').click();
//   await page.getByPlaceholder('Search').click();
//   await page.getByPlaceholder('Search').click();
//   await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('Tanjina');
  await page.locator('.btn.btn-sm.btn-success').click();
  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').press('ControlOrMeta+a');
  await page.getByPlaceholder('Search').fill('Dolon');
  await page.locator('.btn.btn-sm.btn-success').click();
  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('jayed');
  await page.locator('.btn.btn-sm.btn-success').click();
  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('Tariq');
  await page.locator('.btn.btn-sm.btn-success').first().click();
  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('Tariq');
  await page.locator('.even > td:nth-child(7) > .btn').click();
  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('Bhi');
  await page.locator('.btn.btn-sm.btn-success').click();
  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('irfa');
  await page.locator('.btn.btn-sm.btn-success').click();
  await page.locator('.col-2').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('parvez');
  await page.locator('.btn.btn-sm.btn-success').click();
  await page.locator('#category_id1').selectOption('7');
  await page.locator('#category_id2').selectOption('7');
  await page.locator('#category_id3').selectOption('7');
  await page.locator('#category_id4').selectOption('7');
  await page.locator('#category_id5').selectOption('7');
  await page.locator('#category_id6').selectOption('7');
  await page.locator('#category_id7').selectOption('7');
  await page.locator('#category_id8').selectOption('7');
  await page.locator('#category_id9').selectOption('7');
  await page.getByRole('row', { name: '1 202526 Md. Ashikur Rahman' }).getByPlaceholder('description').click();
  await page.getByRole('row', { name: '1 202526 Md. Ashikur Rahman' }).getByPlaceholder('description').click();
  await page.getByRole('row', { name: '1 202526 Md. Ashikur Rahman' }).getByPlaceholder('description').fill(monthName + ' team outing');
  await page.getByRole('row', { name: '2 202266 Badrun Nahar Tanjina' }).getByPlaceholder('description').click();
  await page.getByRole('row', { name: '2 202266 Badrun Nahar Tanjina' }).getByPlaceholder('description').fill(monthName + ' team outing');
  await page.getByRole('row', { name: '3 202268 Dolon Banik Team' }).getByPlaceholder('description').click();
  await page.getByRole('row', { name: '3 202268 Dolon Banik Team' }).getByPlaceholder('description').fill(monthName + ' team outing');
  await page.getByRole('row', { name: '4 202306 Jayed Ibrahim Team' }).getByPlaceholder('description').click();
  await page.getByRole('row', { name: '4 202306 Jayed Ibrahim Team' }).getByPlaceholder('description').fill(monthName + ' team outing');
  await page.getByRole('row', { name: '5 202245 Syed Tariq Hassan' }).getByPlaceholder('description').click();
  await page.getByRole('row', { name: '5 202245 Syed Tariq Hassan' }).getByPlaceholder('description').fill(monthName + ' team outing');
  await page.getByRole('row', { name: '6 202524 Md Tariqur Rahman' }).getByPlaceholder('description').click();
  await page.getByRole('row', { name: '6 202524 Md Tariqur Rahman' }).getByPlaceholder('description').fill(monthName + ' team outing');
  await page.locator('tr:nth-child(7) > td:nth-child(6) > .form-control').click();
  await page.locator('tr:nth-child(7) > td:nth-child(6) > .form-control').fill(monthName + ' team outing');
  await page.locator('tr:nth-child(8) > td:nth-child(6) > .form-control').click();
  await page.locator('tr:nth-child(8) > td:nth-child(6) > .form-control').fill(monthName + ' team outing');
  await page.locator('tr:nth-child(9) > td:nth-child(6) > .form-control').click();
  await page.locator('tr:nth-child(9) > td:nth-child(6) > .form-control').fill(monthName + ' team outing');
  await page.getByRole('textbox', { name: 'Special Note.' }).click();
  await page.getByRole('textbox', { name: 'Special Note.' }).fill('Team outing bill, ' + monthName + '-' + year);


  await page.getByRole('row', { name: '1 202526 Md. Ashikur Rahman' }).getByPlaceholder('Amount').click();
  await page.getByRole('row', { name: '1 202526 Md. Ashikur Rahman' }).getByPlaceholder('Amount').click();
  await page.getByRole('row', { name: '1 202526 Md. Ashikur Rahman' }).getByPlaceholder('Amount').fill(amount);
  await page.getByRole('row', { name: '2 202266 Badrun Nahar Tanjina' }).getByPlaceholder('Amount').click();
  await page.getByRole('row', { name: '2 202266 Badrun Nahar Tanjina' }).getByPlaceholder('Amount').fill(amount);
  await page.getByRole('row', { name: '3 202268 Dolon Banik Team' }).getByPlaceholder('Amount').click();
  await page.getByRole('row', { name: '3 202268 Dolon Banik Team' }).getByPlaceholder('Amount').fill(amount);
  await page.getByRole('row', { name: '4 202306 Jayed Ibrahim Team' }).getByPlaceholder('Amount').click();
  await page.getByRole('row', { name: '4 202306 Jayed Ibrahim Team' }).getByPlaceholder('Amount').fill(amount);
  await page.getByRole('row', { name: '5 202245 Syed Tariq Hassan' }).getByPlaceholder('Amount').click();
  await page.getByRole('row', { name: '5 202245 Syed Tariq Hassan' }).getByPlaceholder('Amount').fill(amount);
  await page.getByRole('row', { name: '6 202524 Md Tariqur Rahman' }).getByPlaceholder('Amount').click();
  await page.getByRole('row', { name: '6 202524 Md Tariqur Rahman' }).getByPlaceholder('Amount').fill(amount);
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .form-control').click();
  await page.locator('tr:nth-child(7) > td:nth-child(7) > .form-control').fill(amount);
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .form-control').click();
  await page.locator('tr:nth-child(8) > td:nth-child(7) > .form-control').fill(amount);
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .form-control').click();
  await page.locator('tr:nth-child(9) > td:nth-child(7) > .form-control').fill(amount);

  await page.pause();
});